[tool.black]
line-length = 100
target-version = ["py311"]
include = "\.(py|pyi)$"

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["app_utils"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
per-file-ignores = {
    "__init__.py" = ["F401"],
}
